version: '3.0'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  web:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
    links:
      - db
    environment:
      - DB_HOST=db:3306
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=wordpress
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
